// Lookup pricing par nom d'outil (insensible à la casse)
const TOOL_PRICING = {
  // Hébergement
  'railway':        'freemium',
  'vercel':         'freemium',
  'netlify':        'freemium',
  'ovh mutualisé':  'subscription',
  'ovh vps':        'subscription',
  'aws':            'payant',
  'render':         'freemium',
  'fly.io':         'freemium',
  'digitalocean':   'payant',
  'hetzner':        'payant',
  // Base de données
  'postgresql':     'gratuit',
  'mysql':          'gratuit',
  'mongodb':        'freemium',
  'sqlite':         'gratuit',
  'supabase':       'freemium',
  'planetscale':    'freemium',
  'redis':          'freemium',
  // Frontend
  'react':          'gratuit',
  'next.js':        'gratuit',
  'vue.js':         'gratuit',
  'nuxt':           'gratuit',
  'svelte':         'gratuit',
  'astro':          'gratuit',
  'html/css vanilla': 'gratuit',
  'angular':        'gratuit',
  // Backend
  'node.js/express':   'gratuit',
  'python/fastapi':    'gratuit',
  'python/django':     'gratuit',
  'php/laravel':       'gratuit',
  'nestjs':            'gratuit',
  'ruby on rails':     'gratuit',
  // Auth
  'jwt maison':        'gratuit',
  'auth0':             'freemium',
  'clerk':             'freemium',
  'supabase auth':     'freemium',
  'nextauth.js':       'gratuit',
  'keycloak':          'gratuit',
  // Emails
  'nodemailer/smtp':   'gratuit',
  'resend':            'freemium',
  'sendgrid':          'freemium',
  'mailgun':           'freemium',
  'brevo':             'freemium',
  'postmark':          'freemium',
  // Devtools
  'vs code':           'gratuit',
  'claude code':       'subscription',
  'github':            'freemium',
  'gitlab':            'freemium',
  'docker':            'freemium',
  'cursor':            'subscription',
  // Domaine
  'ovh':               'subscription',
  'namecheap':         'subscription',
  'cloudflare':        'freemium',
  'gandi':             'subscription',
  // CMS
  'wordpress':         'freemium',
  'strapi':            'freemium',
  'sanity':            'freemium',
  'contentful':        'freemium',
  'notion':            'freemium',
  // Paiement
  'stripe':            'payant',
  'paypal':            'payant',
  'lemon squeezy':     'payant',
  'paddle':            'payant',
  // Analytics
  'plausible':         'subscription',
  'google analytics':  'gratuit',
  'posthog':           'freemium',
  'sentry':            'freemium',
  'umami':             'freemium',
};

// Mapping outil → clé de catégorie techStack (format JSON stocké en DB)
export const TOOL_CAT_KEY = {
  'railway': 'hebergement', 'vercel': 'hebergement', 'netlify': 'hebergement',
  'ovh mutualisé': 'hebergement', 'ovh vps': 'hebergement', 'aws': 'hebergement',
  'render': 'hebergement', 'fly.io': 'hebergement', 'digitalocean': 'hebergement',
  'hetzner': 'hebergement',
  'postgresql': 'bdd', 'mysql': 'bdd', 'mongodb': 'bdd', 'sqlite': 'bdd',
  'supabase': 'bdd', 'planetscale': 'bdd', 'redis': 'bdd',
  'react': 'frontend', 'vue.js': 'frontend', 'next.js': 'frontend', 'nuxt': 'frontend',
  'svelte': 'frontend', 'astro': 'frontend', 'html/css vanilla': 'frontend', 'angular': 'frontend',
  'node.js/express': 'backend', 'python/fastapi': 'backend', 'python/django': 'backend',
  'php/laravel': 'backend', 'nestjs': 'backend', 'ruby on rails': 'backend',
  'jwt maison': 'auth', 'auth0': 'auth', 'clerk': 'auth', 'supabase auth': 'auth',
  'nextauth.js': 'auth', 'keycloak': 'auth',
  'nodemailer/smtp': 'emails', 'resend': 'emails', 'sendgrid': 'emails',
  'mailgun': 'emails', 'brevo': 'emails', 'postmark': 'emails',
  'vs code': 'devtools', 'claude code': 'devtools', 'github': 'devtools',
  'gitlab': 'devtools', 'docker': 'devtools', 'cursor': 'devtools',
  'ovh': 'domaine', 'namecheap': 'domaine', 'cloudflare': 'domaine', 'gandi': 'domaine',
};

export const CAT_LABELS = {
  hebergement: 'Hébergement',
  bdd:         'Base de données',
  frontend:    'Framework frontend',
  backend:     'Framework backend',
  auth:        'Authentification',
  emails:      "Envoi d'emails",
  devtools:    'Outils de développement',
  domaine:     'Domaine',
};

// Extrait tous les noms d'outils sélectionnés depuis un objet techStack JSON
export function extractStackToolNames(techStack) {
  const names = new Set();
  if (!techStack || typeof techStack !== 'object') return names;
  for (const key of Object.keys(CAT_LABELS)) {
    const selected = techStack[key] || [];
    for (const item of selected) {
      const label = item === 'Autre' ? (techStack[`${key}_autre`] || null) : item;
      if (label) names.add(label.toLowerCase().trim());
    }
  }
  return names;
}

// Retourne la clé de catégorie d'un outil (pour mise à jour project.techStack)
export function getCategoryKey(toolName) {
  if (!toolName) return null;
  return TOOL_CAT_KEY[toolName.toLowerCase().trim()] || null;
}

export const PRICING_CONFIG = {
  gratuit:      { label: 'Gratuit',    color: 'bg-green-100 text-green-700',   dot: '🟢' },
  freemium:     { label: 'Freemium',   color: 'bg-yellow-100 text-yellow-700', dot: '🟡' },
  payant:       { label: 'Payant',     color: 'bg-blue-100 text-blabia-blue',     dot: '🔵' },
  subscription: { label: 'Abonnement', color: 'bg-orange-100 text-orange-700', dot: '🟠' },
};

export function getPricing(toolName) {
  if (!toolName) return null;
  return TOOL_PRICING[toolName.toLowerCase()] || null;
}

// ── Boîte à outils v4.0 ──────────────────────────────────────────────────────

export const TOOLBOX_CATEGORIES = [
  {
    id: 'hosting',
    label: 'Hébergement',
    categoryDescription: 'Où vit ton site web ou ton application — le serveur qui le rend accessible sur internet',
    icon: '🌐',
    required: true,
    tools: [
      {
        id: 'railway',
        label: 'Railway',
        pricing: 'freemium',
        pricingDetail: 'Gratuit jusqu\'à 5$/mois de ressources, puis ~5€/mois',
        role: 'Héberge ton application web automatiquement depuis GitHub',
        description: 'Plateforme cloud simple qui déploie ton code automatiquement. La plus facile pour débuter.',
        compatibleWith: ['postgresql', 'mysql', 'mongodb', 'node-express', 'python-fastapi', 'php-laravel'],
        incompatibleWith: [],
        recommended: true,
        complexity: 'simple',
      },
      {
        id: 'vercel',
        label: 'Vercel',
        pricing: 'freemium',
        pricingDetail: 'Gratuit pour les projets perso, ~20$/mois pour les équipes',
        role: 'Héberge ton site ou app Next.js avec déploiement en 1 clic',
        description: 'Optimisé pour Next.js et les sites frontend. Déploiement instantané depuis GitHub.',
        compatibleWith: ['react', 'next.js', 'vue.js', 'postgresql', 'mongodb', 'supabase'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'simple',
      },
      {
        id: 'netlify',
        label: 'Netlify',
        pricing: 'freemium',
        pricingDetail: 'Gratuit pour les sites statiques, ~19$/mois Pro',
        role: 'Héberge ton site web statique sans serveur',
        description: 'Idéal pour les sites statiques (React/Vue sans backend). Ne supporte pas Node.js ni Python côté serveur.',
        compatibleWith: ['react', 'vue.js', 'html-css'],
        incompatibleWith: ['node-express', 'python-fastapi', 'php-laravel'],
        recommended: false,
        complexity: 'simple',
      },
      {
        id: 'ovh-vps',
        label: 'OVH VPS',
        pricing: 'subscription',
        pricingDetail: 'À partir de ~5€/mois',
        role: 'Serveur privé que tu contrôles entièrement',
        description: 'Serveur virtuel privé. Plus de flexibilité mais nécessite des connaissances en administration serveur.',
        compatibleWith: ['postgresql', 'mysql', 'mongodb', 'node-express', 'python-fastapi', 'php-laravel'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'advanced',
      },
      {
        id: 'aws',
        label: 'AWS',
        pricing: 'payant',
        pricingDetail: 'À la consommation — peut vite devenir coûteux sans surveillance',
        role: 'Infrastructure cloud professionnelle complète',
        description: 'Amazon Web Services — la référence enterprise. Très puissant mais complexe à maîtriser.',
        compatibleWith: ['postgresql', 'mysql', 'mongodb', 'node-express', 'python-fastapi'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'advanced',
      },
    ],
  },
  {
    id: 'database',
    label: 'Base de données',
    categoryDescription: 'Où sont stockées les données de ton application — utilisateurs, produits, messages…',
    icon: '🗄️',
    required: true,
    tools: [
      {
        id: 'postgresql',
        label: 'PostgreSQL',
        pricing: 'gratuit',
        pricingDetail: 'Gratuit et open source',
        role: 'Stocke tes données de façon fiable et structurée',
        description: 'La base de données relationnelle la plus populaire. Parfaite pour 99% des projets web.',
        compatibleWith: ['railway', 'vercel', 'aws', 'node-express', 'python-fastapi', 'python-django', 'php-laravel'],
        incompatibleWith: [],
        recommended: true,
        complexity: 'simple',
      },
      {
        id: 'mysql',
        label: 'MySQL',
        pricing: 'gratuit',
        pricingDetail: 'Gratuit et open source',
        role: 'Stocke tes données de façon structurée, très répandu en PHP',
        description: 'Alternative à PostgreSQL, très utilisée avec PHP/Laravel et WordPress.',
        compatibleWith: ['railway', 'aws', 'php-laravel'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'simple',
      },
      {
        id: 'mongodb',
        label: 'MongoDB',
        pricing: 'freemium',
        pricingDetail: 'Tier gratuit 512MB, puis ~9$/mois',
        role: 'Stocke des données flexibles sans structure rigide',
        description: 'Base de données NoSQL. Idéale pour des données variées ou des prototypes rapides.',
        compatibleWith: ['railway', 'aws', 'node-express'],
        incompatibleWith: ['php-laravel'],
        recommended: false,
        complexity: 'medium',
      },
      {
        id: 'supabase',
        label: 'Supabase',
        pricing: 'freemium',
        pricingDetail: 'Gratuit jusqu\'à 500MB, puis ~25$/mois',
        role: 'Base de données + authentification + stockage en un seul service',
        description: 'PostgreSQL managé avec auth intégrée, API auto-générée et stockage de fichiers. Alternative à Firebase.',
        compatibleWith: ['vercel', 'railway', 'react', 'vue.js', 'next.js'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'simple',
      },
      {
        id: 'sqlite',
        label: 'SQLite',
        pricing: 'gratuit',
        pricingDetail: 'Totalement gratuit et intégré',
        role: 'Base de données ultra-simple intégrée à l\'application',
        description: 'Parfaite pour les prototypes, apps desktop ou projets locaux. Déconseillée en prod cloud.',
        compatibleWith: ['node-express', 'python-fastapi'],
        incompatibleWith: ['railway', 'vercel'],
        recommended: false,
        complexity: 'simple',
      },
    ],
  },
  {
    id: 'frontend',
    label: 'Interface utilisateur',
    categoryDescription: 'Ce que l\'utilisateur voit et avec quoi il interagit dans son navigateur',
    icon: '🎨',
    required: true,
    tools: [
      {
        id: 'react',
        label: 'React',
        pricing: 'gratuit',
        pricingDetail: 'Gratuit et open source (Meta)',
        role: 'Crée des interfaces utilisateur interactives',
        description: 'La bibliothèque frontend la plus utilisée au monde. Parfaite pour les apps dynamiques.',
        compatibleWith: ['node-express', 'python-fastapi', 'railway', 'vercel', 'postgresql', 'mongodb'],
        incompatibleWith: [],
        recommended: true,
        complexity: 'medium',
      },
      {
        id: 'next.js',
        label: 'Next.js',
        pricing: 'gratuit',
        pricingDetail: 'Gratuit et open source (Vercel)',
        role: 'React avec rendu serveur et optimisations SEO incluses',
        description: 'Framework React avec SSR/SSG. Parfait pour les sites qui doivent être bien référencés.',
        compatibleWith: ['vercel', 'railway', 'postgresql', 'mongodb', 'supabase'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'medium',
      },
      {
        id: 'vue.js',
        label: 'Vue.js',
        pricing: 'gratuit',
        pricingDetail: 'Gratuit et open source',
        role: 'Crée l\'interface utilisateur de ton application',
        description: 'Alternative à React, souvent jugée plus accessible. Grande communauté francophone.',
        compatibleWith: ['node-express', 'php-laravel', 'railway', 'vercel'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'medium',
      },
      {
        id: 'html-css',
        label: 'HTML / CSS vanilla',
        pricing: 'gratuit',
        pricingDetail: 'Natif au navigateur, gratuit',
        role: 'Crée des pages web simples sans framework',
        description: 'Le b.a.-ba du web. Parfait pour les sites vitrines ou projets sans interactivité complexe.',
        compatibleWith: ['netlify', 'ovh-vps'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'simple',
      },
    ],
  },
  {
    id: 'backend',
    label: 'Logique serveur',
    categoryDescription: 'Le cerveau de ton application — gère les données, les utilisateurs et les règles métier',
    icon: '⚙️',
    required: false,
    tools: [
      {
        id: 'node-express',
        label: 'Node.js / Express',
        pricing: 'gratuit',
        pricingDetail: 'Gratuit et open source',
        role: 'Fait tourner ton application côté serveur en JavaScript',
        description: 'JavaScript côté serveur. Idéal si tu connais déjà JS pour le frontend. Très répandu.',
        compatibleWith: ['postgresql', 'mysql', 'mongodb', 'railway', 'react', 'vue.js'],
        incompatibleWith: [],
        recommended: true,
        complexity: 'medium',
      },
      {
        id: 'python-fastapi',
        label: 'Python / FastAPI',
        pricing: 'gratuit',
        pricingDetail: 'Gratuit et open source',
        role: 'Fait tourner ton application serveur en Python',
        description: 'Moderne et performant. Idéal pour les APIs et les projets avec IA/machine learning.',
        compatibleWith: ['postgresql', 'mongodb', 'railway'],
        incompatibleWith: ['nodemailer'],
        recommended: false,
        complexity: 'medium',
      },
      {
        id: 'php-laravel',
        label: 'PHP / Laravel',
        pricing: 'gratuit',
        pricingDetail: 'Gratuit et open source',
        role: 'Fait tourner ton application serveur en PHP',
        description: 'PHP moderne avec une structure élégante. Très utilisé pour les sites web classiques.',
        compatibleWith: ['mysql', 'postgresql', 'ovh-vps'],
        incompatibleWith: ['mongodb', 'nodemailer'],
        recommended: false,
        complexity: 'medium',
      },
    ],
  },
  {
    id: 'auth',
    label: 'Authentification',
    categoryDescription: 'Comment tes utilisateurs se connectent et prouvent leur identité sur ton application',
    icon: '🔐',
    required: false,
    tools: [
      {
        id: 'jwt-maison',
        label: 'JWT maison',
        pricing: 'gratuit',
        pricingDetail: 'Gratuit — tu codes toi-même',
        role: 'Gère les connexions utilisateurs avec tes propres règles',
        description: 'Tu codes l\'authentification de A à Z avec des tokens JWT. Contrôle total, plus de travail.',
        compatibleWith: ['node-express', 'python-fastapi', 'php-laravel'],
        incompatibleWith: [],
        recommended: true,
        complexity: 'medium',
      },
      {
        id: 'clerk',
        label: 'Clerk',
        pricing: 'freemium',
        pricingDetail: 'Gratuit jusqu\'à 10 000 utilisateurs actifs/mois, puis ~25$/mois',
        role: 'Authentification clé en main sans coder',
        description: 'Service d\'authentification tout intégré. Interface personnalisable, très simple avec React/Next.js.',
        compatibleWith: ['react', 'next.js', 'node-express'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'simple',
      },
      {
        id: 'supabase-auth',
        label: 'Supabase Auth',
        pricing: 'freemium',
        pricingDetail: 'Inclus avec Supabase (gratuit jusqu\'à 50 000 utilisateurs)',
        role: 'Authentification incluse dans ta base Supabase',
        description: 'Si tu utilises Supabase, l\'auth est comprise. Email/mot de passe et providers sociaux.',
        compatibleWith: ['supabase', 'react', 'next.js', 'vue.js'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'simple',
      },
    ],
  },
  {
    id: 'emails',
    label: "Envoi d'emails",
    categoryDescription: 'Le service qui envoie des emails depuis ton application — confirmations, notifications, invitations',
    icon: '📧',
    required: false,
    tools: [
      {
        id: 'resend',
        label: 'Resend',
        pricing: 'freemium',
        pricingDetail: 'Gratuit jusqu\'à 3 000 emails/mois, puis ~20$/mois',
        role: 'Envoie des emails depuis ton application',
        description: 'Service d\'envoi d\'emails moderne avec API simple et logs intégrés. Très populaire.',
        compatibleWith: ['node-express', 'python-fastapi', 'railway'],
        incompatibleWith: [],
        recommended: true,
        complexity: 'simple',
      },
      {
        id: 'nodemailer',
        label: 'Nodemailer / SMTP',
        pricing: 'gratuit',
        pricingDetail: 'Gratuit si tu as un serveur SMTP (Gmail, OVH…)',
        role: 'Envoie des emails via un serveur SMTP existant',
        description: 'Bibliothèque Node.js pour SMTP. Gratuit mais configuration manuelle requise.',
        compatibleWith: ['node-express', 'railway', 'ovh-vps'],
        incompatibleWith: ['python-fastapi', 'php-laravel'],
        recommended: false,
        complexity: 'medium',
      },
      {
        id: 'sendgrid',
        label: 'SendGrid',
        pricing: 'freemium',
        pricingDetail: 'Gratuit jusqu\'à 100 emails/jour, puis ~20$/mois',
        role: 'Envoie des emails en masse de façon fiable',
        description: 'Solution email entreprise. Bonne délivrabilité et analytics intégrés.',
        compatibleWith: ['node-express', 'python-fastapi', 'php-laravel'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'medium',
      },
    ],
  },
  {
    id: 'devtools',
    label: 'Outils de développement',
    categoryDescription: 'Les logiciels pour écrire ton code, gérer tes versions et collaborer avec d\'autres développeurs',
    icon: '🛠️',
    required: false,
    tools: [
      {
        id: 'vscode',
        label: 'VS Code',
        pricing: 'gratuit',
        pricingDetail: 'Gratuit et open source (Microsoft)',
        role: 'L\'éditeur où tu écris ton code',
        description: 'L\'éditeur de code le plus populaire au monde. Léger, extensible, compatible avec tout.',
        compatibleWith: [],
        incompatibleWith: [],
        recommended: true,
        complexity: 'simple',
      },
      {
        id: 'github',
        label: 'GitHub',
        pricing: 'freemium',
        pricingDetail: 'Gratuit pour les projets publics et perso, ~4$/mois Teams',
        role: 'Sauvegarde et partage ton code, gère l\'historique des modifications',
        description: 'La plateforme Git la plus utilisée. Indispensable pour sauvegarder et déployer ton code.',
        compatibleWith: ['railway', 'vercel', 'netlify'],
        incompatibleWith: [],
        recommended: true,
        complexity: 'simple',
      },
      {
        id: 'claude-code',
        label: 'Claude Code',
        pricing: 'subscription',
        pricingDetail: 'Inclus dans l\'abonnement Claude Pro (~22$/mois)',
        role: 'Assistant IA qui code avec toi dans ton terminal',
        description: 'L\'outil IA que tu utilises via BlabIA. Écrit, explique et corrige du code en langage naturel.',
        compatibleWith: [],
        incompatibleWith: [],
        recommended: true,
        complexity: 'simple',
      },
      {
        id: 'docker',
        label: 'Docker',
        pricing: 'freemium',
        pricingDetail: 'Gratuit pour un usage dev et perso',
        role: 'Emballe ton application pour qu\'elle fonctionne partout identiquement',
        description: 'Conteneurise ton application. Élimine les problèmes "ça marche sur ma machine". Requis pour certains déploiements.',
        compatibleWith: ['railway', 'aws', 'ovh-vps'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'advanced',
      },
    ],
  },
  {
    id: 'domain',
    label: 'Nom de domaine',
    categoryDescription: 'L\'adresse de ton site web — ce que les gens tapent dans leur navigateur pour t\'accéder',
    icon: '🔗',
    required: false,
    tools: [
      {
        id: 'ovh-domain',
        label: 'OVH',
        pricing: 'subscription',
        pricingDetail: 'À partir de ~10€/an pour un .fr ou .com',
        role: 'Achète et gère ton nom de domaine en français',
        description: 'Registrar français. Simple, fiable, support en français. Idéal pour les .fr.',
        compatibleWith: ['railway', 'vercel', 'netlify'],
        incompatibleWith: [],
        recommended: true,
        complexity: 'simple',
      },
      {
        id: 'cloudflare',
        label: 'Cloudflare',
        pricing: 'freemium',
        pricingDetail: 'Domaine au prix coûtant (~8$/an) + CDN gratuit inclus',
        role: 'Domaine + protection + accélération de ton site en un',
        description: 'Registrar avec CDN et protection DDoS gratuits. Le meilleur rapport qualité/prix pour les projets sérieux.',
        compatibleWith: ['railway', 'vercel', 'netlify', 'ovh-vps', 'aws'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'medium',
      },
      {
        id: 'namecheap',
        label: 'Namecheap',
        pricing: 'subscription',
        pricingDetail: 'À partir de ~8$/an',
        role: 'Achète et gère ton nom de domaine',
        description: 'Registrar international bon marché. Interface simple et support 24/7.',
        compatibleWith: ['railway', 'vercel', 'netlify'],
        incompatibleWith: [],
        recommended: false,
        complexity: 'simple',
      },
    ],
  },
];

// Construit une map d'incompatibilité bidirectionnelle depuis TOOLBOX_CATEGORIES
export function buildIncompatMap(categories) {
  const map = new Map();
  for (const cat of categories) {
    for (const tool of cat.tools) {
      if (!map.has(tool.id)) map.set(tool.id, new Set());
      for (const otherId of (tool.incompatibleWith || [])) {
        map.get(tool.id).add(otherId);
        if (!map.has(otherId)) map.set(otherId, new Set());
        map.get(otherId).add(tool.id);
      }
    }
  }
  return map;
}
